CREATE DATABASE metalurgica
GO
USE metalurgica
GO


CREATE TABLE setor(
    Id_setor UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Nome VARCHAR (100)
);

CREATE TABLE maquina(
    Id_Maquina UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Nome VARCHAR (100),
    Id_setor UNIQUEIDENTIFIER FOREIGN KEY REFERENCES setor(Id_setor),
);

CREATE TABLE OS(
    Id_OS UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Data_Abertura DATE,
    Problema_Relatado VARCHAR(100),
    Id_Maquina UNIQUEIDENTIFIER FOREIGN KEY REFERENCES maquina(Id_Maquina)
);

DROP TABLE setor;

CREATE TABLE Tecnicos(
    Id_Tecnicos UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Nome VARCHAR(100),
    Especialidade VARCHAR(50)
);

CREATE TABLE OS_Tecnicos(
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Id_OS UNIQUEIDENTIFIER FOREIGN KEY REFERENCES OS(Id_OS),
    Id_Tecnicos UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Tecnicos(Id_Tecnicos)
);
